name: Release ioscross

on:
  push:
    tags:
      - "v*"

jobs:
  package_sdks:
    uses: ./.github/workflows/sdk.yml

  release_sdks:
    name: Release SDKs
    runs-on: ubuntu-latest
    needs: package_sdks
    steps:
      - uses: actions/checkout@v4

      - name: Download SDKs
        id: download_sdks
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            execSync('npm install @actions/artifact');
            const { DefaultArtifactClient } = require('@actions/artifact');
            const artifact = new DefaultArtifactClient();
            const fs = require('fs');

            const allArtifacts = await artifact.listArtifacts();
            const sdkArtifacts = allArtifacts.artifacts.filter(a => !a.name.startsWith('sdk-'));
            for (const sdkArtifact of sdkArtifacts) {
              console.log('download', sdkArtifact);
              await artifact.downloadArtifact(sdkArtifact.id, {
                path: '.'
              });
            }

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          files: |
            ./*.sdk.tar.xz
